// -------------------------------------------------------------------
// Author: WANG JUN
// Date: 2025/08/26
// Description:
//MaterialApp needs to add the localized delegate generated by your module
// localizationsDelegates: const [
//   NetworkFailureLocalizations.delegate,
//   // ... other delegate
// ],
// supportedLocales: NetworkFailureLocalizations.supportedLocales,
//
// Override 451 prompts or TLS prompts to be stricter
// runApp(ProviderScope(
//   overrides: [
//     networkI18nConfigProvider.overrideWithValue(NetworkI18nConfig(
//       httpStatusOverrides: { 451: (s) => s.http_other(451) /* or custom key */ },
//       codeOverrides: {
//         NetErrCode.tls: (s, _) => s.net_tls, // You can also change it to a more detailed prompt
//       },
//     )),
//   ],
//   child: const MyApp(),
// ));
// -------------------------------------------------------------------
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'network_failure_localizer.dart';

//Configuration Provider that can be overridden by the App
final networkI18nConfigProvider = Provider<NetworkI18nConfig>(
  (_) => const NetworkI18nConfig(),
);

final networkFailureLocalizerProvider =
    Provider<NetworkFailureLocalizer>((ref) {
  final cfg = ref.watch(networkI18nConfigProvider);
  return NetworkFailureLocalizer(config: cfg);
});
