name: app
description: app module
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0

  theme:
    path: ../core/theme
  plugin:
    path: ../core/plugin

  settings:
    path: ../features/settings