name: app
description: app module
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  flutter_dotenv: ^5.2.1

  theme:
    path: ../core/theme
  plugin:
    path: ../core/plugin
  contracts:
    path: ../core/contracts
  di:
    path: ../core/di
  widgets:
    path: ../shared/widgets

  settings:
    path: ../features/settings
  auth:
    path: ../features/auth
  poyopoyo_weather:
    path: ../features/weather
  locale:
    path: ../core/locale

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
#  assets: