name: error_lab
description: error lab module
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  contracts:
    path: ../../core/contracts
  di:
    path: ../../core/di
  plugin:
    path: ../../core/plugin
  network_failure_i18n:
    path: ../../network/net_i18n
  network_dio_retrofit:
    path: ../../network/network_dio_retrofit
  domain:
    path: ../../shared/domain
  action_policy:
    path: ../../core/action_policy
  ui:
    path: ../../shared/ui
  localization:
    path: ../../shared/localization
  business_failure_i18n:
    path: ../../shared/business_failure_i18n

  flutter_riverpod: ^2.6.1
  go_router: ^16.1.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  json_serializable: ^6.10.0
  retrofit_generator: ^10.0.1
  freezed: ^3.2.0
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true